# This workflow will run tests using node and then publish a package to GitHub Packages when a release is created
# For more information see: https://help.github.com/actions/language-and-framework-guides/publishing-nodejs-packages

name: Electron app
on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: windows-latest
    env:
      BUILD_ONLY: false
      BUILD_DEBUG: false
      DEBUG: electron-builder
      AWS_ACCESS_KEY_ID: ${{ secrects.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrects.AWS_SECRET_ACCESS_KEY }}
      S3_BUCKET: download.testmace.com
      DESTINATION_DIRECTORY: yarn-to-npm
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 12
      - run: node upload-to-aws.js
